name: Web deploy on staging

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-staging.yml'
      - '.now/**'
      - 'public/**'
      - 'src/**'
      - 'package.json'

jobs:
  deploy-staging:
    name: Web deploy on staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'

      - name: Install Now CLI
        run: |
          sudo npm install --global --unsafe-perm now

      - name: Deploy to Now
        run: |
          now --token $ZEIT_TOKEN --local-config .now/now.json --prod --confirm
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
